---

- name: Docker Compose Generator
  tags:
    - docker
    - docker_compose
  block:

    - name: Create {{ docker_compose_generator_default_local_compose_output_path }}
      ansible.builtin.file:
        path: "{{ docker_compose_generator_default_local_compose_output_path }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: false
      when:
        - docker_compose_generator_default_local_compose_output is defined
        - docker_compose_generator_default_local_compose_output
        - docker_compose_generator_default_local_compose_output_path is defined
        - docker_compose_generator_default_local_compose_output_path != ""

    - name: Ansible | Set Fact | docker_apps_path
      ansible.builtin.set_fact:
        docker_apps_path: "{{ playbook_dir }}/../{{ docker_compose_generator_docker_app_directory }}"
      run_once: true
      delegate_to: localhost

    - name: Install Docker and Docker Compose
      ansible.builtin.include_tasks:
        file: 'install_docker.yaml'

    - name: Create default docker volume bind directory {{ docker_compose_generator_default_bind_path }}
      ansible.builtin.file:
        path: "{{ docker_compose_generator_default_bind_path }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Docker | Create list of apps to deploy
      become: false
      ansible.builtin.find:
        paths: "{{ docker_apps_path }}"
        file_type: directory
        recurse: false
      delegate_to: localhost
      register: docker_apps_folders

    - name: Get ansible host Architecture details # Required for tag to digest conversion
      ansible.builtin.include_tasks:
        file: 'detect_architecture.yaml'

    - name: Generate Docker Compose files
      ansible.builtin.include_tasks:
        file: 'generate_template.yaml'
      loop: "{{ docker_apps_folders.files | map(attribute='path') | map('basename') | list | unique }}"
      loop_control:
        label: "{{ docker_app }}"
        loop_var: 'docker_app'
      tags:
        - docker_compose

    - name: Docker | Prune images
      community.docker.docker_prune:
        images: true

# For all docker apps, create external network if it doesn't exist
# For all docker apps, move any files to destination
# Install Portainer only
# For all docker apps but portainer, move compose files to repo
