repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.0
  hooks:
    - id: check-github-workflows
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
      # ignore formatting-prettier to have an accurate prettier comparison
      exclude: >
        (?x)^(
          test/eco/.*.result|
          examples/yamllint/.*|
          test/fixtures/formatting-before/.*|
          test/fixtures/formatting-prettier/.*
        )$
    - id: trailing-whitespace
      exclude: >
        (?x)^(
          examples/playbooks/(with-skip-tag-id|unicode).yml|
          examples/playbooks/example.yml|
          examples/yamllint/.*|
          test/eco/.*.result|
          test/fixtures/formatting-before/.*
        )$
    - id: mixed-line-ending
    - id: fix-byte-order-marker
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: debug-statements
      language_version: python3
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell
      exclude: >
        (?x)^(
          .config/dictionary.txt|
          examples/broken/encoding.j2|
          test/schemas/negative_test/.*|
          test/schemas/test/.*|
          src/ansiblelint/schemas/.*\.json
        )$
      additional_dependencies:
        - tomli
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.37.1
  hooks:
    - id: yamllint
      exclude: >
        (?x)^(
          playbooks/.*|
          roles/.*|
        )$
      files: \.(yaml|yml)$
      types: [file, yaml]
      entry: yamllint --strict
- repo: https://github.com/ansible/ansible-lint.git
  rev: v25.5.0
  hooks:
    - id: ansible-lint
      files: ^playbooks/.*\.(yaml|yml)$|^roles/.*\.(yaml|yml)$
      name: Ansible Lint
      description: Run configurations on .ansible-lint file
      verbose: true
      args:
        - --config-file=.ansible-lint
        - -p
