---
- name: Load users ands groups variables
  ansible.builtin.include_vars:
    dir: '../vars'
    files_matching: 'linux_*.' # linux_users && linux_groups

- name: Ubuntu | Create extra groups
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    "{{ mandatory_groups | default([]) }}" # playbooks/vars/linux_groups.yaml
  tags: groups

- name: Linux | Users | Create all required users
  ansible.builtin.user:
    name: "{{ linux_user.name }}"
    comment: "{{ linux_user.comment | default('Created by ansible') }}"
    groups: "{{ linux_user.groups }}"
    append: true
    shell: "{{ linux_user.shell | default('/bin/bash') }}"
  loop: "{{ users.values() }}" # playbooks/vars/linux_users.yaml
  loop_control:
    label: "{{ linux_user.name }}"
    loop_var: 'linux_user'
  register:
    created_users
  when: users is defined and users | length > 0

- name: Linux | Groups | Create all required groups
  ansible.builtin.group:
    name: "{{ item }}"
  loop: "{{ users.values() | map(attribute='groups') | flatten | unique }}"
  register:
    created_groups
  when: users is defined and users | length > 0
