---
- name: Load users ands groups variables
  ansible.builtin.include_vars:
    dir: '../vars'
    files_matching: 'apt_*.'

- name: Linux | APT | Install Packages
  ansible.builtin.include_role:
    name: install_software
  tags:
    - apt
    - packages
